name: 'Development'

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout dev'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: npm ci
    - name: 'Run build'
      run: npm run build-dev clientId=${{ secrets.TRAKT_CLIENT_ID }} clientSecret=${{ secrets.TRAKT_CLIENT_SECRET }} analyticsId=${{ secrets.GOOGLE_ANALYTICS_ID }} rollbarToken=${{ secrets.ROLLBAR_TOKEN }} tmdbApiKey=${{ secrets.TMDB_API_KEY }} chromeExtensionKey=${{ secrets.CHROME_EXTENSION_KEY }} firefoxExtensionId=${{ secrets.FIREFOX_EXTENSION_ID }}
    - name: 'Zip dist'
      run: npm run zip
    - name: 'Run tests'
      run: xvfb-run npm test