name: 'Development'

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout dev'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: npm ci
    - name: 'Run build'
      run: npm run build-dev
    - name: 'Zip dist'
      run: npm run zip
    - name: 'Run tests'
      run: xvfb-run npm test