name: 'Development'

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout dev'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: npm ci
    - if: github.repository == 'rafaelgssa/traktflix'
      name: 'Generate config.json'
      run: "echo \"{ \\\"development\\\": { \\\"clientId\\\": \\\"${{ secrets.TRAKT_CLIENT_ID }}\\\", \\\"clientSecret\\\": \\\"${{ secrets.TRAKT_CLIENT_SECRET }}\\\", \\\"analyticsId\\\": \\\"${{ secrets.GOOGLE_ANALYTICS_ID }}\\\", \\\"rollbarToken\\\": \\\"${{ secrets.ROLLBAR_TOKEN }}\\\", \\\"tmdbApiKey\\\": \\\"${{ secrets.TMDB_API_KEY }}\\\", \\\"chromeExtensionKey\\\": \\\"${{ secrets.CHROME_EXTENSION_KEY }}\\\", \\\"firefoxExtensionId\\\": \\\"${{ secrets.FIREFOX_EXTENSION_ID }}\\\" } }\" >> ./config.json"
    - if: github.repository == 'rafaelgssa/traktflix'
      name: 'Run build'
      run: npm run build-dev
    - if: github.repository == 'rafaelgssa/traktflix'
      name: 'Zip dist'
      run: npm run zip
    - name: 'Run tests'
      run: xvfb-run npm test